set right cache strategy
diverta/front_next_media pull request #18
Opened 2024-02-16 10:16 UTC by VortexExpansion

Fixes #6 

Please review 
@HisashiHasebe @yabe-diverta san

## For reviewers
- Please delete the `.next` and `node modules` from root directory and run `npm install` and `npm run dev` again
- This step is important because it will remove the existing API cache stored in the `.next` files and create a new cache instance

## Updated cache strategy
- The results for almost all `GET` requests will be cached for performance boost and since we expect the backend data to not change as frequently. 

- cache `no-store` is set only for :

`/rcms-api/1/content/details/${id}` : because fav_cnt count is updated frequently on details page
`/rcms-api/1/ranking` : dependent on number of likes
`/rcms-api/1/my_favorite_list` : dependent on logged in user's likes

2024-02-20 07:17 UTC, HisashiHasebe commented
No need `no-store` to `/rcms-api/1/member/me` ?

Other than that, I think it is OK if GithubActions are run when content is updated and reflected on the front page. (Next's cache does not misbehave).

 I will check from the front end after the build error is resolved.

2024-02-26 05:47 UTC, VortexExpansion commented
@HisashiHasebe san

On investigation I found that `/rcms-api/1/member/me` works fine without using `no-store` so I still think it won't be necessary. 

Though I would like to request @yabe-diverta san to also confirm this once.

2024-02-26 06:03 UTC, HisashiHasebe commented
@VortexExpansion 
> On investigation I found that /rcms-api/1/member/me still works fine without using no-store
so I think it won't be necessary.

Is it okay to have `no-store` on `/rcms-api/1/member/me`? 
If we want to cache, we don't set no-store; if not, we set no-store. I think it's better to unify the approach based on these reasons.

2024-02-26 06:58 UTC, VortexExpansion commented
@HisashiHasebe san
Yes it is OK to have but not necessary to have. 

I did not use `no-store` because we want to cache the current member info so that we don't have to fetch the same information on every request because this information is not being updated frequently so it is more optimal to fetch the request from database once and then use the cache for every other call to prevent calling overhead. 

My understanding is that when different users are logged in, fetching the request once and then using their stored cache for every other call within their local is most optimum performance wise. 

I'm sorry if I'm still missing your perspective. Please let me know. 🙇

2024-03-08 04:37 UTC, yabe-diverta commented
@VortexExpansion @HisashiHasebe 

Sry for you, due to manager's claim, we have to make all the frontend-fetch to be dynamic.
https://github.com/diverta/front_nuxt_corporate/issues/14

For novice users, we should not to have
- server-side fetch / prefetch
- client fetch cache
because some ppl would get confused that why A content is always fresh but B content has been stale unless build.
This case is A is client fetch without cache, B is prefetch on server-side.

To not to give frustrations to those users I think we need to make all fetch to be client fetch w/o cache.

2024-03-08 05:44 UTC, VortexExpansion commented
@yabe-diverta san
Ok will make all fetch requests CSR

2024-03-29 06:44 UTC, yabe-diverta commented
@VortexExpansion 
Sry for waiting you so much, found this issue is unable to merge due to [my update](https://github.com/diverta/front_next_media/pull/11).
I had done drastically change for entire codebase, would you rework over it?  😅

2024-04-10 09:15 UTC, VortexExpansion commented
Progress for client side fetching : 
- [ ] article/[id]
- [x] contact
- [ ] feature/[id]
- [ ] login
- [x] member/delete
- [x] member/edit 
- [ ] member/limited[id]
- [x] member/mypage
- [ ] register
- [ ] reminder
- [ ] index

2024-04-10 10:13 UTC, yabe-diverta requested changes
reviewed, check pls 🙇

2024-04-10 10:13 UTC, yabe-diverta commented on src/app/page.jsx
I think Page component should be server component.
Because we can define server/client boundary if we extract client portions to component,
and can use Suspect/ErrorBoundary for it.
Please extract ranking component from this.

2024-04-10 10:13 UTC, yabe-diverta commented on src/components/common/TagArea.jsx
BTW how do you think about error handler on client?
Should we make a popup for it?

2024-04-10 10:14 UTC, yabe-diverta commented on src/components/common/TagArea.jsx
> Thinking of doing redirection and snackbar integration in a different PR as this is independent from CSR behaviour intended for now

Ah got it.
resolve this.

2024-04-10 10:15 UTC, VortexExpansion commented on src/components/common/TagArea.jsx
@yabe-diverta san
I think we can use a snackbar like popup for this later ?

2024-04-10 10:17 UTC, VortexExpansion commented on src/app/page.jsx
Ok 👍 
@yabe-diverta san
Can you clarify the below statement ? 
`Please extract ranking component from this.`

Do I keep TagArea, TagKeyword as CSR 
And make Ranking a separate component and make that CSR as well ?

2024-04-10 10:38 UTC, yabe-diverta commented on src/app/page.jsx
> Do I keep TagArea, TagKeyword as CSR
And make Ranking a separate component and make that CSR as well ?

Yes.
[check this raticle (sry for JP)](https://zenn.dev/tm35/articles/0a64177c0a41bd) if you are interested.

2024-04-10 11:09 UTC, VortexExpansion commented on src/app/page.jsx
Resolved

2024-04-16 08:38 UTC, VortexExpansion commented
All dynamic pages to be handled separately in https://github.com/diverta/front_next_media/issues/21
Marking this ready for review now. 

@yabe-diverta san

2024-04-16 08:42 UTC, yabe-diverta requested changes
reviewed 🙇

2024-04-16 08:42 UTC, yabe-diverta commented on src/components/section/feature/Feature.jsx
> +  // const data = await getFeatureList();
remove?

2024-04-16 09:05 UTC, VortexExpansion commented on src/components/section/feature/Feature.jsx
> +  // const data = await getFeatureList();
Done

2024-04-19 16:54 UTC, merged